version: "3"
services:
  app:
    container_name: apache
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - 8085:80
    volumes:
      - .:/var/www/html
    links:
      - postgresContainer

  postgresContainer:
    container_name: postgres
    image: postgres:12.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=adminer_db

  adminer:
    container_name: adminer
    image: adminer:4.7.5
    ports:
      - 8087:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgresContainer
    links:
      - postgresContainer
