version: "3"
services:
  app:
    container_name: apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:80
    volumes:
      - .:/var/www/html
#    links:
#      - mysql
#  mysql:
#    container_name: container_mysql
#    image: mysql:5.7
#    ports:
#      - 33061:3306
#    volumes:
#      - ./mysql:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=1
#      - MYSQL_USER=root
#      - MYSQL_DATABASE=crud
